Ramon/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SiniestroController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('hola');
})->name('inicio');

Route::resource('siniestro',SiniestroController::class);

Ramon/app/Models/Siniestro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Jenssegers\Mongodb\Eloquent\Model;

class Siniestro extends Model
{
    protected $collection = 'siniestro_collection';

    protected $connection = 'mongodb';

    protected $fillable = [
        'fecha_levantamiento',
            'hora',
            'ficha',
            'sexo',
            'edad',
            'fecha_incidente',
            'vialidad_1',
            'vialidad_2',
            'colonia',
            'causa_detallada',
            'accidente',
            'tipo_vehiculo',
            'vehiculo',
            'vialidad_uno',
            'vialidad_uno_otra',
            'carriles_uno',
            'limites_uno',
            'vialidad_uno_trans',
            'vialidad_dos',
            'vialidad_dos_otra',
            'carriles_dos',
            'limites_dos',
            'vialidad_dos_trans',
            'elementos_urbanos_vialidad_uno',
            'control_transito_vialidad_uno',
            'senaletica_horizontal_vialidad_uno',
            'senaletica_vertical_vialidad_uno',
            'elementos_urbanos_vialidad_dos',
            'control_transito_vialidad_dos',
            'senaletica_horizontal_vialidad_dos',
            'senaletica_vertical_vialidad_dos',
            'ciclovia',
            'tipo_segregada',
            'ciclista_otra',
            'tipo_segregador',
            'segregador_otra',
            'rodamiento',
            'mal_estado',
            'croquis',
            'coordenadas',
            'redaccion_hechos',
            'fotos'
    ];
}

Ramon/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'fecha',
        'hora',
        'calle_numero',
        'tipo_vialidad',
        'colonia',
        'municipio',
        'tipo_vehiculo',
        'tipo_siniestro',
    ];
}

Ramon/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Ramon/app/Http/Controllers/SiniestroController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Siniestro;
use App\Traits\ImageUpload;
use App\Http\Requests\StoreSiniestroRequest;

class SiniestroController extends Controller
{
    use ImageUpload;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = Siniestro::all()->last();
        $ficha = 0;
        if($id == null){
            $ficha = 1;
        }
        else{
            $ficha = $id->ficha + 1;
        } 
	    return view("moncho",['ficha' => $ficha ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSiniestroRequest $request)
    {
        
        $validated = $request->validated();

        $siniestro = new Siniestro([
            'fecha_levantamiento' => $request->fecha_levantamiento,
            'hora'=> $request->hora,
            'ficha' => $request->ficha,
            'sexo' => $request->sexo,
            'edad' => $request->edad,
            'fecha_incidente' => $request->fecha_incidente,
            'vialidad_1' => $request->vialidad_1,
            'vialidad_2' => $request->vialidad_2,
            'colonia' => $request->colonia,
            'causa_detallada' => $request->causa_detallada,
            'accidente' => $request->accidente,
            'vehiculo' => $request->vehiculo,
            'tipo_vehiculo' => $request->tipo_vehiculo,
            'vialidad_uno' => $request->vialidad_uno,
            'vialidad_uno_otra' => $request->vialidad_uno_otra,
            'carriles_uno' => $request->carriles_uno,
            'limites_uno' => $request->limites_uno,
            'vialidad_uno_trans' => $request->vialidad_uno_trans,
            'vialidad_dos' => $request->vialidad_dos,
            'vialidad_dos_otra' => $request->vialidad_dos_otra,
            'carriles_dos' => $request->carriles_dos,
            'limites_dos' => $request->limites_dos,
            'vialidad_dos_trans' => $request->vialidad_dos_trans,
            'elementos_urbanos_vialidad_uno' => $request->elementos_urbanos_vialidad_uno,
            'control_transito_vialidad_uno' => $request->control_transito_vialidad_uno,
            'senaletica_horizontal_vialidad_uno' => $request->senaletica_horizontal_vialidad_uno,
            'senaletica_vertical_vialidad_uno' => $request->senaletica_vertical_vialidad_uno,
            'elementos_urbanos_vialidad_dos' => $request->elementos_urbanos_vialidad_dos,
            'control_transito_vialidad_dos' => $request->control_transito_vialidad_dos,
            'senaletica_horizontal_vialidad_dos' => $request->senaletica_horizontal_vialidad_dos,
            'senaletica_vertical_vialidad_dos' => $request->senaletica_vertical_vialidad_dos,
            'ciclovia' => $request->ciclovia,
            'tipo_segregada' => $request->tipo_segregada,
            'ciclista_otra' => $request->ciclista_otra,
            'tipo_segregador' => $request->tipo_segregador,
            'segregador_otra' => $request->segregador_otra,
            'rodamiento' => $request->rodamiento,
            'mal_estado' => $request->mal_estado,
            'croquis' => $request->croquis,
            'coordenadas' => $request->coordenadas,
            'redaccion_hechos' => $request->redaccion_hechos,
            'fotos' => $request->fotos
        ]);

        if($siniestro->croquis && $siniestro->fotos){
            try {
                $filePath = $this->SiniestroImageUpload($siniestro->croquis);
                $filaPath2 = $this->SiniestroImageUpload($siniestro->fotos);  //Passing $data->image as parameter to our created method
                $siniestro->croquis = $filePath;
                $siniestro->fotos = $filaPath2;
                $siniestro->save();
                return view('hola');

            } catch (Exception $e) {
           //Write your error message here
            }
        }
        
        $siniestro->save();
        
        return view('ramon');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

Ramon/resources/views/datetime.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Datepicker</title>
    <link rel="stylesheet" href="./styles/style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
</head>

<body>
    <main class="container">
        <header class="col-sm-12">
            <img src="./images/banner.png" alt="Page Banner" width="800px" height="130px">
            <span>Bootstrap Calender</span>
        </header>
        <section class="col-sm-12">
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>

        </section>
        <footer>

        </footer>
    </main>
    <script type="text/javascript">
        $(function() {
            $('#datetimepicker1').datetimepicker();
        });
    </script>
</body>

</html>

Ramon/resources/views/hola.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <center>
    <h1>Formulario de Hechos viales ciclistas</h1>
    <center>
    <a href="{{ route("siniestro.index") }}">si quieres llenar un formulario da click aqui</a>
</body>
</html>

Ramon/resources/views/ramon.blade.php
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
        <title>Siniestro</title>
    </head>
    <body>
        <div class="container-fluid">
            <!-- Content here -->
            <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
                <div class="container-md">
                    <a class="navbar-brand" href="#">Formulario de siniestros de ciclistas</a>
                </div>
            </nav>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> datos requeridos<br><br>
                    <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{ route('siniestro.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="input-group mb-5">
                    <span class="input-group-text">Fecha y Hora</span>
                    <input type="text" aria-label="First name"  id="fecha" name="fecha" class="form-control">
                    <input type="text" aria-label="Last name" id="hora" name="hora" class="form-control">
                </div>
                <div class="input-group mb-5">
                    <input type="text" class="form-control" id="calle" name="calle" placeholder="Calle">
                    <span class="input-group-text">y</span>
                    <input type="text" class="form-control" id="numero" name="numero" placeholder="Numero">
                </div>
                <div class="input-group mb-5">
                    <span class="input-group-text" id="basic-addon1">Tipo de vialidad</span>
                    <input type="text" class="form-control" id="tipo_vialidad" name="tipo_vialidad" placeholder="Ingrese el tipo de vialidad" aria-label="Username" aria-describedby="basic-addon1">
                </div>  
                <div class="input-group mb-5">
                    <span class="input-group-text" id="basic-addon1">Colonia</span>
                    <input type="text" class="form-control" id="colonia" name="colonia" placeholder="Ingrese la colonia" aria-label="Username" aria-describedby="basic-addon1">
                </div>
                <div class="input-group mb-5">
                    <span class="input-group-text" id="basic-addon1">Municipio</span>
                    <input type="text" class="form-control" id="municipio" name="municipio" placeholder="Ingrese el municipio" aria-label="Username" aria-describedby="basic-addon1">
                </div>
                <div class="input-group mb-5">
                    <span class="input-group-text" id="basic-addon1">Tipo de Vehiculo</span>
                    <input type="text" class="form-control" id="tipo_vehiculo" name="tipo_vehiculo" placeholder="Ingrese el tipo de vehiculo" aria-label="Username" aria-describedby="basic-addon1">
                </div>
                <div class="input-group mb-5">
                    <span class="input-group-text" id="basic-addon1">Tipo de Siniestro</span>
                    <input type="text" class="form-control" id="tipo_siniestro" name="tipo_siniestro" placeholder="Ingrese el tipo de siniestro" aria-label="Username" aria-describedby="basic-addon1">
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                    vialidad
                    </label>
                </div>
                <div class="d-grid gap-2 col-2 mb-3 mx-auto">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>   
            </form>
        </div>
    </body>
    </html>